### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by jamen**

### CODE REVIEW

**Comment by dy** [comment]
Awesome @jamen thanks! Going to tackle audio-speaker - a real bummer for the whole audiojs

**Comment by jamen** [comment]
@dfcreative Awesome, yeah.  It's pretty tough for me.  I've been tinkering with it locally but still haven't got something stable.  Trying bindings to other libraries too, taking inspiration from [node-libao](https://github.com/ezequielgarcia/node-libao)

**Comment by jamen** [comment]
FWIW, I'm creating the MIT licenses with this script:

```
npx -q license | sed "s/Jamen Marz/$(npx -q npe author)/" > LICENSE
```

The copyright based off package.json might be a little inconsistent.

**Comment by dy** [comment]
Good to know! It is better than nothing, thanks!

**Pull request merged**
